name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## NxtClone Release ${{ github.ref_name }}
          
          ### Features
          - Remote monitoring and management
          - Cross-platform agents (Windows, Linux)
          - Real-time system metrics
          - Auto-update functionality
          - Web-based dashboard
          
          ### Installation
          1. Download source code
          2. Run `npm install` in root directory
          3. Start server with `npm start`
          4. Install agent dependencies: `pip install -r agents/requirements.txt`
          5. Run agents on target machines
          
          ### Auto-Update
          Agents will automatically update from this release.
        draft: false
        prerelease: false