name: Update README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Update README with latest info
      run: |
        # Get current date
        DATE=$(date '+%Y-%m-%d')
        
        # Update README with current version and date
        sed -i "s/Last Updated: .*/Last Updated: $DATE/" README.md || echo "# Last Updated: $DATE" >> README.md
        
        # Count files and add stats
        TOTAL_FILES=$(find . -type f -name "*.js" -o -name "*.py" | wc -l)
        echo "" >> README.md
        echo "## Project Stats" >> README.md
        echo "- Total Code Files: $TOTAL_FILES" >> README.md
        echo "- Last Updated: $DATE" >> README.md
    
    - name: Commit README updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "Auto-update README with latest stats"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}